SRCS=$(wildcard src/*.cpp) $(wildcard tool/*.cpp)
OBJS=$(patsubst %.cpp,%.o,$(SRCS))
DEPS=$(wildcard include/quimby/*.h)
CXXFLAGS:=-Iinclude -fopenmp -O3 $(CXXFLAGS)

quimby-static: $(OBJS)
	$(CXX) -static -o $@ $^ $(CXXFLAGS)

clean:
	rm -f $(OBJS)
	rm -f quimby-static
	